# Generated by Django 4.0.4 on 2023-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=400)),
                ('passo1', models.CharField(max_length=100)),
                ('passo2', models.CharField(max_length=100)),
                ('passo3', models.CharField(max_length=100)),
                ('passo4', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Intermediário'), ('C', 'Básico'), ('A', 'Avancado')], default='C', max_length=1),
        ),
    ]
