# Generated by Django 4.0.4 on 2023-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_tarefas_alter_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='data',
            field=models.DateField(default='0001-01-01', max_length=10),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='horario',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avancado'), ('C', 'Básico'), ('B', 'Intermediário')], default='C', max_length=1),
        ),
    ]
