# Generated by Django 4.0.4 on 2023-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_tarefas_data_tarefas_horario_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('C', 'Básico'), ('B', 'Intermediário'), ('A', 'Avancado')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data',
            field=models.DateField(default='0000-00-00', max_length=10),
        ),
    ]
