# Generated by Django 4.0.4 on 2023-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_curso_nivel_alter_tarefas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avancado'), ('B', 'Intermediário'), ('C', 'Básico')], default='C', max_length=1),
        ),
    ]
