# Generated by Django 4.0.4 on 2023-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_alter_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='passo5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Intermediário'), ('A', 'Avancado'), ('C', 'Básico')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data',
            field=models.DateField(default='0000', max_length=10),
        ),
    ]
