# Generated by Django 4.0.4 on 2023-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_tarefas_passo5_alter_curso_nivel_alter_tarefas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('C', 'Básico'), ('A', 'Avancado'), ('B', 'Intermediário')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
