# Generated by Django 4.0.4 on 2023-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_usuario_alter_curso_nivel_alter_tarefas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avancado'), ('B', 'Intermediário'), ('C', 'Básico')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='horario',
            field=models.CharField(default='00:00', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='passo1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='passo2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='passo3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='passo4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='passo5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
