# Generated by Django 4.0.4 on 2023-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_alter_curso_nivel_alter_tarefas_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Intermediário'), ('C', 'Básico'), ('A', 'Avancado')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data',
            field=models.DateField(default='0001-01-01', max_length=10),
        ),
    ]
